apiVersion: v1
kind: Service
metadata:
  name: xrootd-frontend
  labels:
    app: xrootd-gateway
spec:
  type: NodePort
  selector:
    app: xrootd-gateway
  ports:
  - name: xrootd
    protocol: TCP
    port: 1094
    targetPort: 1094
