apiVersion: apps/v1
kind: Deployment
metadata:
  name: "xrootd-gw"
  labels:
    app: xrootd-gateway
    tier: xrootd-gw
spec:
  selector:
    matchLabels:
      tier: xrootd-gw
      app: xrootd-gateway
  template:
    metadata:
      labels:
        tier: xrootd-gw
        app: xrootd-gateway
    spec:
      securityContext:
        runAsUser: 991
        runAsGroup: 988
      containers:
        - name: xrootd-gateway
          image: harbor.stfc.ac.uk/raltier1_xrootd/xrootd-kubernetes/gateway@sha256:48072d5e67b45366d1e5251c5b08962f730ef75a10a1b15fb4cb202349990043
          ports:
          - containerPort: 1094
            name: xrootd-port
          volumeMounts:
            - name: gateway
              mountPath: "/etc/gateway"
              readOnly: true
            - name: ceph-config
              mountPath: /etc/xrootd/xrootd-ceph.cfg
              readOnly: true
            - name: cephsum
              mountPath: /etc/xrootd/xrd_cephsum.sh
              readOnly: true
            - name: tokens
              mountPath: /etc/xrootd/scitokens.cfg
              readOnly: true
            - name: ceph
              mountPath: /etc/ceph
              readOnly: true
              #- name: healthcheck
              #mountPath: /usr/bin/xrootd-health-gateway
            - name: xrdtpc
              mountPath: /etc/xrootd/xrdcp-tpc.sh
            - name: namelib
              mountPath: /etc/xrootd/storage.xml
            - name: fntest
              mountPath: /tmp/fn
            - name: grid-security
              mountPath: /etc/grid-security
              readOnly: true
            - name: macaroon-secret
              mountPath: /etc/xrootd/macaroon-secret
              readOnly: true 
            - name: robots
              mountPath: /etc/xrootd/robots.txt
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: grid-security
          hostPath:
            path: /etc/grid-security
        - name: gateway
          hostPath:
            path: /etc/xrootd
        - name: ceph-config
          hostPath:
            path: /etc/xrootd/xrootd-unified.cfg
        - name: cephsum
          hostPath:
            path: /etc/xrootd/xrd_cephsum.sh
        - name: ceph
          hostPath:
            path: /etc/ceph
            #- name: healthcheck
            #hostPath:
            #path: /usr/bin/xrootd-health-gateway
        - name: tokens
          hostPath:
            path: /etc/xrootd/scitokens.cfg
        - name: xrdtpc
          hostPath:
            path: /etc/xrootd/xrdcp-tpc.sh
        - name: namelib
          hostPath:
            path: /etc/xrootd/storage.xml
        - name: fntest
          hostPath:
            path: /tmp/fntest
        - name: macaroon-secret
          hostPath:
            path: /etc/xrootd/macaroon-secret
        - name: robots
          hostPath:
            path: /etc/xrootd/robots.txt
