apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: xrootd-gateway
  ports:
    - protocol: TCP
      port: 1094
      targetPort: 1094
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
